spring.application.name=configserver
server.port=8012

#===================================== FOR NATIVE ==========================
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/app-config


#===================================== FOR GIT ==========================
#spring.profile.active=git
#spring.cloud.config.server.git.uri=https://github.com/SkillsMetrix/sunlife-api
#spring.cloud.config.server.git.username=connect@skillsmetrix.com
#spring.cloud.config.server.git.password=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
#spring.cloud.config.server.git.clone-on-start=true
#spring.cloud.config.server.git.default-label=main